/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtoV9RouteImport } from './routes/proto/v9'
import { Route as ProtoV8RouteImport } from './routes/proto/v8'
import { Route as ProtoV5RouteImport } from './routes/proto/v5'
import { Route as ProtoV4RouteImport } from './routes/proto/v4'
import { Route as ProtoV3RouteImport } from './routes/proto/v3'
import { Route as ProtoV2RouteImport } from './routes/proto/v2'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV9Route = ProtoV9RouteImport.update({
  id: '/proto/v9',
  path: '/proto/v9',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV8Route = ProtoV8RouteImport.update({
  id: '/proto/v8',
  path: '/proto/v8',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV5Route = ProtoV5RouteImport.update({
  id: '/proto/v5',
  path: '/proto/v5',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV4Route = ProtoV4RouteImport.update({
  id: '/proto/v4',
  path: '/proto/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV3Route = ProtoV3RouteImport.update({
  id: '/proto/v3',
  path: '/proto/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV2Route = ProtoV2RouteImport.update({
  id: '/proto/v2',
  path: '/proto/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/kanban': typeof KanbanRoute
  '/manager': typeof ManagerRoute
  '/proto/v2': typeof ProtoV2Route
  '/proto/v3': typeof ProtoV3Route
  '/proto/v4': typeof ProtoV4Route
  '/proto/v5': typeof ProtoV5Route
  '/proto/v8': typeof ProtoV8Route
  '/proto/v9': typeof ProtoV9Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/kanban': typeof KanbanRoute
  '/manager': typeof ManagerRoute
  '/proto/v2': typeof ProtoV2Route
  '/proto/v3': typeof ProtoV3Route
  '/proto/v4': typeof ProtoV4Route
  '/proto/v5': typeof ProtoV5Route
  '/proto/v8': typeof ProtoV8Route
  '/proto/v9': typeof ProtoV9Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/dashboard': typeof DashboardRoute
  '/kanban': typeof KanbanRoute
  '/manager': typeof ManagerRoute
  '/proto/v2': typeof ProtoV2Route
  '/proto/v3': typeof ProtoV3Route
  '/proto/v4': typeof ProtoV4Route
  '/proto/v5': typeof ProtoV5Route
  '/proto/v8': typeof ProtoV8Route
  '/proto/v9': typeof ProtoV9Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/kanban'
    | '/manager'
    | '/proto/v2'
    | '/proto/v3'
    | '/proto/v4'
    | '/proto/v5'
    | '/proto/v8'
    | '/proto/v9'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/kanban'
    | '/manager'
    | '/proto/v2'
    | '/proto/v3'
    | '/proto/v4'
    | '/proto/v5'
    | '/proto/v8'
    | '/proto/v9'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/dashboard'
    | '/kanban'
    | '/manager'
    | '/proto/v2'
    | '/proto/v3'
    | '/proto/v4'
    | '/proto/v5'
    | '/proto/v8'
    | '/proto/v9'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DashboardRoute: typeof DashboardRoute
  KanbanRoute: typeof KanbanRoute
  ManagerRoute: typeof ManagerRoute
  ProtoV2Route: typeof ProtoV2Route
  ProtoV3Route: typeof ProtoV3Route
  ProtoV4Route: typeof ProtoV4Route
  ProtoV5Route: typeof ProtoV5Route
  ProtoV8Route: typeof ProtoV8Route
  ProtoV9Route: typeof ProtoV9Route
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v9': {
      id: '/proto/v9'
      path: '/proto/v9'
      fullPath: '/proto/v9'
      preLoaderRoute: typeof ProtoV9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v8': {
      id: '/proto/v8'
      path: '/proto/v8'
      fullPath: '/proto/v8'
      preLoaderRoute: typeof ProtoV8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v5': {
      id: '/proto/v5'
      path: '/proto/v5'
      fullPath: '/proto/v5'
      preLoaderRoute: typeof ProtoV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v4': {
      id: '/proto/v4'
      path: '/proto/v4'
      fullPath: '/proto/v4'
      preLoaderRoute: typeof ProtoV4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v3': {
      id: '/proto/v3'
      path: '/proto/v3'
      fullPath: '/proto/v3'
      preLoaderRoute: typeof ProtoV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v2': {
      id: '/proto/v2'
      path: '/proto/v2'
      fullPath: '/proto/v2'
      preLoaderRoute: typeof ProtoV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DashboardRoute: DashboardRoute,
  KanbanRoute: KanbanRoute,
  ManagerRoute: ManagerRoute,
  ProtoV2Route: ProtoV2Route,
  ProtoV3Route: ProtoV3Route,
  ProtoV4Route: ProtoV4Route,
  ProtoV5Route: ProtoV5Route,
  ProtoV8Route: ProtoV8Route,
  ProtoV9Route: ProtoV9Route,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
