/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtoV9RouteImport } from './routes/proto/v9'
import { Route as ProtoV8RouteImport } from './routes/proto/v8'
import { Route as ProtoV5RouteImport } from './routes/proto/v5'
import { Route as ProtoV4RouteImport } from './routes/proto/v4'
import { Route as ProtoV3RouteImport } from './routes/proto/v3'
import { Route as ProtoV2RouteImport } from './routes/proto/v2'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedOfficeRouteImport } from './routes/_authenticated/office'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV9Route = ProtoV9RouteImport.update({
  id: '/proto/v9',
  path: '/proto/v9',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV8Route = ProtoV8RouteImport.update({
  id: '/proto/v8',
  path: '/proto/v8',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV5Route = ProtoV5RouteImport.update({
  id: '/proto/v5',
  path: '/proto/v5',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV4Route = ProtoV4RouteImport.update({
  id: '/proto/v4',
  path: '/proto/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV3Route = ProtoV3RouteImport.update({
  id: '/proto/v3',
  path: '/proto/v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoV2Route = ProtoV2RouteImport.update({
  id: '/proto/v2',
  path: '/proto/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfficeRoute = AuthenticatedOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/ai': typeof AuthenticatedAiRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/office': typeof AuthenticatedOfficeRoute
  '/test': typeof AuthenticatedTestRoute
  '/proto/v2': typeof ProtoV2Route
  '/proto/v3': typeof ProtoV3Route
  '/proto/v4': typeof ProtoV4Route
  '/proto/v5': typeof ProtoV5Route
  '/proto/v8': typeof ProtoV8Route
  '/proto/v9': typeof ProtoV9Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/ai': typeof AuthenticatedAiRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/manager': typeof AuthenticatedManagerRoute
  '/office': typeof AuthenticatedOfficeRoute
  '/test': typeof AuthenticatedTestRoute
  '/proto/v2': typeof ProtoV2Route
  '/proto/v3': typeof ProtoV3Route
  '/proto/v4': typeof ProtoV4Route
  '/proto/v5': typeof ProtoV5Route
  '/proto/v8': typeof ProtoV8Route
  '/proto/v9': typeof ProtoV9Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRoute
  '/_authenticated/office': typeof AuthenticatedOfficeRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/proto/v2': typeof ProtoV2Route
  '/proto/v3': typeof ProtoV3Route
  '/proto/v4': typeof ProtoV4Route
  '/proto/v5': typeof ProtoV5Route
  '/proto/v8': typeof ProtoV8Route
  '/proto/v9': typeof ProtoV9Route
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/ai'
    | '/docs'
    | '/kanban'
    | '/manager'
    | '/office'
    | '/test'
    | '/proto/v2'
    | '/proto/v3'
    | '/proto/v4'
    | '/proto/v5'
    | '/proto/v8'
    | '/proto/v9'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/ai'
    | '/docs'
    | '/kanban'
    | '/manager'
    | '/office'
    | '/test'
    | '/proto/v2'
    | '/proto/v3'
    | '/proto/v4'
    | '/proto/v5'
    | '/proto/v8'
    | '/proto/v9'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/ai'
    | '/_authenticated/docs'
    | '/_authenticated/kanban'
    | '/_authenticated/manager'
    | '/_authenticated/office'
    | '/_authenticated/test'
    | '/proto/v2'
    | '/proto/v3'
    | '/proto/v4'
    | '/proto/v5'
    | '/proto/v8'
    | '/proto/v9'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ProtoV2Route: typeof ProtoV2Route
  ProtoV3Route: typeof ProtoV3Route
  ProtoV4Route: typeof ProtoV4Route
  ProtoV5Route: typeof ProtoV5Route
  ProtoV8Route: typeof ProtoV8Route
  ProtoV9Route: typeof ProtoV9Route
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v9': {
      id: '/proto/v9'
      path: '/proto/v9'
      fullPath: '/proto/v9'
      preLoaderRoute: typeof ProtoV9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v8': {
      id: '/proto/v8'
      path: '/proto/v8'
      fullPath: '/proto/v8'
      preLoaderRoute: typeof ProtoV8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v5': {
      id: '/proto/v5'
      path: '/proto/v5'
      fullPath: '/proto/v5'
      preLoaderRoute: typeof ProtoV5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v4': {
      id: '/proto/v4'
      path: '/proto/v4'
      fullPath: '/proto/v4'
      preLoaderRoute: typeof ProtoV4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v3': {
      id: '/proto/v3'
      path: '/proto/v3'
      fullPath: '/proto/v3'
      preLoaderRoute: typeof ProtoV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/v2': {
      id: '/proto/v2'
      path: '/proto/v2'
      fullPath: '/proto/v2'
      preLoaderRoute: typeof ProtoV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/office': {
      id: '/_authenticated/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof AuthenticatedOfficeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRoute
  AuthenticatedOfficeRoute: typeof AuthenticatedOfficeRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRoute,
  AuthenticatedOfficeRoute: AuthenticatedOfficeRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ProtoV2Route: ProtoV2Route,
  ProtoV3Route: ProtoV3Route,
  ProtoV4Route: ProtoV4Route,
  ProtoV5Route: ProtoV5Route,
  ProtoV8Route: ProtoV8Route,
  ProtoV9Route: ProtoV9Route,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
